#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cloud-native-setup
Version  : 1.19
Release  : 17
URL      : https://github.com/clearlinux/cloud-native-setup/archive/refs/tags/v1.19.tar.gz
Source0  : https://github.com/clearlinux/cloud-native-setup/archive/refs/tags/v1.19.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: cloud-native-setup-data = %{version}-%{release}
Requires: cloud-native-setup-license = %{version}-%{release}

%description
## Cloud Native Setup
Automation around setting up the cloud-native content (Kubernetes) on Clear Linux.

%package data
Summary: data components for the cloud-native-setup package.
Group: Data

%description data
data components for the cloud-native-setup package.


%package license
Summary: license components for the cloud-native-setup package.
Group: Default

%description license
license components for the cloud-native-setup package.


%prep
%setup -q -n cloud-native-setup-1.19
cd %{_builddir}/cloud-native-setup-1.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631570249
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1631570249
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cloud-native-setup
cp %{_builddir}/cloud-native-setup-1.19/LICENSE %{buildroot}/usr/share/package-licenses/cloud-native-setup/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/clr-k8s-examples/0-canal/overlays/v3.10/kustomization.yaml
/usr/share/clr-k8s-examples/0-canal/overlays/v3.3/kustomization.yaml
/usr/share/clr-k8s-examples/0-canal/overlays/v3.9/kustomization.yaml
/usr/share/clr-k8s-examples/0-cilium/overlays/v1.6.4/kustomization.yaml
/usr/share/clr-k8s-examples/0-cilium/overlays/v1.6/kustomization.yaml
/usr/share/clr-k8s-examples/0-flannel/overlays/16b0fe66285d1ad1f42b154ab852682f6fafb1a7/kustomization.yaml
/usr/share/clr-k8s-examples/0-flannel/overlays/960b3243b9a7faccdfe7b3c09097105e68030ea7/kustomization.yaml
/usr/share/clr-k8s-examples/1-core-metrics/overlays/v0.3.3/kustomization.yaml
/usr/share/clr-k8s-examples/1-core-metrics/overlays/v0.3.5/kustomization.yaml
/usr/share/clr-k8s-examples/1-core-metrics/overlays/v0.3.6/kustomization.yaml
/usr/share/clr-k8s-examples/2-dashboard/overlays/v1.10.1/kustomization.yaml
/usr/share/clr-k8s-examples/2-dashboard/overlays/v2.0.0-beta2/kustomization.yaml
/usr/share/clr-k8s-examples/3-efk/overlays/v1.15.1/kustomization.yaml
/usr/share/clr-k8s-examples/4-kube-prometheus/overlays/f458e85e5d7675f7bc253072e1b4c8892b51af0f/kustomization.yaml
/usr/share/clr-k8s-examples/4-kube-prometheus/overlays/v0.1.0/kustomization.yaml
/usr/share/clr-k8s-examples/4-kube-prometheus/overlays/v0.2.0/kustomization.yaml
/usr/share/clr-k8s-examples/5-ingres-lb/overlays/nginx-0.25.0/kustomization.yaml
/usr/share/clr-k8s-examples/5-ingres-lb/overlays/nginx-0.25.0/patch_clusterrole.yaml
/usr/share/clr-k8s-examples/5-ingres-lb/overlays/nginx-0.25.1/kustomization.yaml
/usr/share/clr-k8s-examples/5-ingres-lb/overlays/nginx-0.26.1/kustomization.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.7.3/kustomization.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.7.3/patch_configmap.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.8.1/kustomization.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.8.1/patch_configmap.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.8.3/kustomization.yaml
/usr/share/clr-k8s-examples/6-metal-lb/overlays/v0.8.3/patch_configmap.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/multinode/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/multinode/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/multinode/patch_operator.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/standalone/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/standalone/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.0.3/standalone/patch_operator.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.0/multinode/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.0/multinode/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.0/standalone/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.0/standalone/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.1/multinode/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.1/multinode/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.1/standalone/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.1/standalone/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.7/multinode/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.7/multinode/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.7/standalone/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.1.7/standalone/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.2.6/multinode/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.2.6/multinode/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.2.6/standalone/kustomization.yaml
/usr/share/clr-k8s-examples/7-rook/overlays/v1.2.6/standalone/patch_cephcluster.yaml
/usr/share/clr-k8s-examples/8-kata/overlays/1.8.0-kernel-config/kustomization.yaml
/usr/share/clr-k8s-examples/8-kata/overlays/1.8.2-kernel-config/kustomization.yaml
/usr/share/clr-k8s-examples/8-kata/overlays/1.9.1-kernel-config/kustomization.yaml
/usr/share/clr-k8s-examples/9-multi-network/Dockerfile
/usr/share/clr-k8s-examples/9-multi-network/README.md
/usr/share/clr-k8s-examples/9-multi-network/cni/vfioveth
/usr/share/clr-k8s-examples/9-multi-network/multus-sriov-ds.yaml
/usr/share/clr-k8s-examples/9-multi-network/sriov-conf.yaml
/usr/share/clr-k8s-examples/9-multi-network/systemd/sriov.service
/usr/share/clr-k8s-examples/9-multi-network/systemd/sriov.sh
/usr/share/clr-k8s-examples/9-multi-network/test/bridge/0-bridge-net.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/bridge/1-pod-bridge.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/pod.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/sriov/0-sriov-net.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/sriov/1-pod-sriov.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/sriov/2-pod-dpdk-ver.yaml
/usr/share/clr-k8s-examples/9-multi-network/test/sriov/Dockerfile
/usr/share/clr-k8s-examples/DEVELOP.md
/usr/share/clr-k8s-examples/README.md
/usr/share/clr-k8s-examples/Vagrantfile
/usr/share/clr-k8s-examples/admit-kata/README.md
/usr/share/clr-k8s-examples/admit-kata/create-certs.sh
/usr/share/clr-k8s-examples/admit-kata/deploy/webhook-registration.yaml.tpl
/usr/share/clr-k8s-examples/admit-kata/deploy/webhook.yaml
/usr/share/clr-k8s-examples/admit-kata/versions
/usr/share/clr-k8s-examples/containerd_devmapper_setup.sh
/usr/share/clr-k8s-examples/create_stack.sh
/usr/share/clr-k8s-examples/hack/ceph_status.sh
/usr/share/clr-k8s-examples/hack/update_checker.sh
/usr/share/clr-k8s-examples/haproxy.cfg.example
/usr/share/clr-k8s-examples/kubeadm.yaml
/usr/share/clr-k8s-examples/node-feature-discovery/overlays/v0.4.0/kustomization.yaml
/usr/share/clr-k8s-examples/node-problem-detector/overlays/v0.6.6/kustomization.yaml
/usr/share/clr-k8s-examples/node-problem-detector/overlays/v0.6.6/patch_configmap_mce-monitor.yaml
/usr/share/clr-k8s-examples/node-problem-detector/overlays/v0.6.6/patch_configmap_rules.yaml
/usr/share/clr-k8s-examples/reset_stack.sh
/usr/share/clr-k8s-examples/setup_kata_firecracker.sh
/usr/share/clr-k8s-examples/setup_system.sh
/usr/share/clr-k8s-examples/tests/autoscale/load-gen.yaml
/usr/share/clr-k8s-examples/tests/autoscale/php.yaml
/usr/share/clr-k8s-examples/tests/autoscale/test-autoscale.sh
/usr/share/clr-k8s-examples/tests/cpumanager/test-cpumanager.sh
/usr/share/clr-k8s-examples/tests/cpumanager/test-cpumanager.yaml.tmpl
/usr/share/clr-k8s-examples/tests/deploy-svc-ing/test-deploy-kata-fc.yaml
/usr/share/clr-k8s-examples/tests/deploy-svc-ing/test-deploy-kata-qemu.yaml
/usr/share/clr-k8s-examples/tests/deploy-svc-ing/test-deploy-runc.yaml
/usr/share/clr-k8s-examples/tests/deploy-svc-ing/test-ingress-kata.yaml
/usr/share/clr-k8s-examples/tests/deploy-svc-ing/test-ingress-runc.yaml
/usr/share/clr-k8s-examples/tests/e2e/run_e2e.sh
/usr/share/clr-k8s-examples/tests/pvc/wordpress.yaml
/usr/share/clr-k8s-examples/vagrant.md

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cloud-native-setup/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
